name: Check last master commit 
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  check-time:
    name: Check if last commit was 30 minutes ago or more
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 
        with:
          fetch-depth: 0
      - name: Check last commit time
        run: |
          LAST_COMMIT_TIMESTAMP=$(git show -s --format=%ct origin/main);
          NOW_TIMESTAMP=$(date +%s);
          if (( NOW_TIMESTAMP - LAST_COMMIT_TIMESTAMP < 120 )); then
            echo "not allowed";
            exit 1;
          else
            echo "YES allowed";
            exit 0;
          fi;
